version: "3.8"

services:
  rstudio:
    image: nlpsandbox/notebooks:0.1.0
    build:
      context: .
    container_name: nlpsandbox-notebooks
    command: rstudio
    env_file:
      - .env
    volumes:
      - .:/home/rstudio/nlpsandbox:rw
    # networks:
    #   - data-node
    ports:
      - "${HOST_PORT}:8787"

# networks:
#   data-node:
#     external: true
#     name: data-node_default
