version: "3.8"

services:
  rstudio:
    image: nlpsandbox/notebooks:0.1.0
    build:
      context: .
    container_name: nlpsandbox-notebooks
    command: rstudio
    env_file:
      - .env
    volumes:
      - .:/home/rstudio/nlpsandbox:rw
    networks:
      - data-node
      - nlpsandbox
    ports:
      - "${HOST_PORT}:8787"
      - "8888:8888"

networks:
  data-node:
    external: true
    name: data-node_default
  nlpsandbox:
    external: true
    name: phi-annotator-example_nlpsandbox
