version: "3.8"

services:
  rstudio:
    image: nlpsandbox/notebooks:0.1.0
    build:
      context: .
    env_file:
      - .env
    environment:
      - USER=${NOTEBOOK_USER}
    container_name: nlpsandbox-notebooks
    command: rstudio
    # command: jupyter
    volumes:
      - .:/home/${NOTEBOOK_USER}/nlpsandbox:rw
    # networks:
    #   - data-node
    ports:
      - "8787:8787"
      - "8888:8888"

# networks:
#   data-node:
#     external: true
#     name: data-node_default
